hold on;
plot(fftData(1,:));hold on;
% plot(fftData(2,:));hold on;
plot(fftData(3,:));hold on;
% plot(fftData(4,:));hold on;
% plot(fftData(5,:));hold on;
% plot(fftData(6,:));hold on;
% plot(fftData(7,:));hold on;
% plot(fftData(8,:));hold on;
% legend('1','2','3','4','5','6','7','8');
